; Mathematically lossless and the smallest of the lossless options by far. Slow to encode and slow to scrub.
; Use with RenderVideoPreset=lossless in Render.ini

[Preset]
Args=-c:v libx264 -qp 0 -preset veryslow -pix_fmt yuv444p
Ext=mkv
